import { Keypair, SystemProgram } from "@solana/web3.js";


// Path to the keypair generated by the Solana CLI
// Load the keypair from the file
const secretKeyString = process.env.SOLANA_KEYPAIR;
const secretKeyArray = JSON.parse(secretKeyString);
const keypair = Keypair.fromSecretKey(Uint8Array.from(secretKeyArray));

/*
Create a transfer transaction if the user wallet has 0 SOL to allow 
even empty wallets to close lost accounts

@returns the number of lamports sent to the user wallet
*/
export async function addCharityTransfer(userPublicKey, transaction) {
    const charity_lamports = 5000
    
    // Create the transfer instruction for the destination wallet
    const transferInstruction = SystemProgram.transfer({
        fromPubkey: keypair.publicKey,
        toPubkey: userPublicKey,
        lamports: charity_lamports,
    });

    transaction.add(transferInstruction)

    return charity_lamports
}